# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: H:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/Documents/vivado_projs/ES3B2/lab5_20250325/lab5_20250325.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
